# This file was generated by GoReleaser. DO NOT EDIT.
cask "avar" do
  binary "avr", target: "avar"

  version "0.12.1"

  on_macos do
    sha256 "81718091e1d3a28aa72548fc8d3a46f0809f643e0d5eb32992dad2d640dc1015"
    url "https://github.com/olamide226/avar/releases/download/v#{version}/avar_#{version}_darwin_all.tar.gz"
  end

  name "avar"
  desc "Run your current directory in Linux"
  homepage "https://github.com/olamide226/avar"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "lima",
    ]

  binary "avr"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/avr"
    end
  end

  # No zap stanza required
end
