# This file was generated by GoReleaser. DO NOT EDIT.
cask "avar" do
  binary "avr", target: "avar"

  version "0.12.0"

  on_macos do
    sha256 "cc5a46b0db52a39499be964171aee5b622c6dc39f5ec17480c9e353d0295d3ca"
    url "https://github.com/olamide226/avar/releases/download/v#{version}/avar_#{version}_darwin_all.tar.gz"
  end

  name "avar"
  desc "Run your current directory in Linux"
  homepage "https://github.com/olamide226/avar"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "lima",
    ]

  binary "avr"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/avr"
    end
  end

  # No zap stanza required
end
