# This file was generated by GoReleaser. DO NOT EDIT.
cask "avar" do
  binary "avr", target: "avar"

  version "0.12.4"

  on_macos do
    sha256 "8ad021936c63f099390f112401ec4bdedd06e08d02176d7588ff1b8a904a6791"
    url "https://github.com/olamide226/avar/releases/download/v#{version}/avar_#{version}_darwin_all.tar.gz"
  end

  name "avar"
  desc "Run your current directory in Linux"
  homepage "https://github.com/olamide226/avar"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "lima",
    ]

  binary "avr"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/avr"
    end
  end

  # No zap stanza required
end
